---
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Check GPG key
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: keyrings_docker_gpg

- name: Add GPG key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: keyrings_docker_gpg.stat.exists == False

- name: Check APT line
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_list

- name: Add APT line
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    apt-get update
  when: docker_list.stat.exists == False

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-ce-rootless-extras
      - uidmap

- name: Disable system-wide Docker service
  systemd:
    name: docker
    state: stopped
    enabled: no
