---
- name: Create user
  user:
    name: trs-user
    shell: /usr/bin/bash

- name: Install prerequisites
  apt:
    name:
      - qemu-user-static
      - acl

- name: Check Docker rootless availability
  become_user: trs-user
  shell: |
    /bin/bash -lc "
      docker ps
    "
  failed_when: docker_availability.rc not in [0, 1]
  register: docker_availability

- name: enable linger
  shell: |
    loginctl enable-linger trs-user
  when: docker_availability.rc == 1

- name: Enable Docker rootless
  become_user: trs-user
  shell: |
    /bin/bash -lc "
      echo 'export XDG_RUNTIME_DIR=/run/user/$(id -u trs-user)' >> ~/.bash_profile
      source ~/.bash_profile
      dockerd-rootless-setuptool.sh install

      echo 'export PATH=/usr/bin:$PATH' >> ~/.bash_profile
      echo 'export DOCKER_HOST=unix:///run/user/$(id -u trs-user)/docker.sock' >> ~/.bash_profile

      source ~/.bash_profile
      docker run hello-world
    "
  when: docker_availability.rc == 1

- name: Clone
  ansible.builtin.git:
    repo: https://github.com/keyasuda/trip-routing-system.git
    dest: /home/trs-user/app/trip-routing-system
  become_user: trs-user
