---
- name: Create user
  user:
    name: trs-user
    shell: /usr/bin/bash

- name: Install prerequisites
  apt:
    name:
      - qemu-user-static
      - acl

- name: Check Docker rootless availability
  become_user: trs-user
  shell: |
    /bin/bash -lc "
      docker ps
    "
  failed_when: docker_availability.rc not in [0, 1]
  register: docker_availability

- name: enable linger
  shell: |
    loginctl enable-linger trs-user
  when: docker_availability.rc == 1

- name: Enable Docker rootless
  become_user: trs-user
  shell: |
    /bin/bash -lc "
      echo 'export XDG_RUNTIME_DIR=/run/user/$(id -u trs-user)' >> ~/.bash_profile
      source ~/.bash_profile
      dockerd-rootless-setuptool.sh install

      echo 'export PATH=/usr/bin:$PATH' >> ~/.bash_profile
      echo 'export DOCKER_HOST=unix:///run/user/$(id -u trs-user)/docker.sock' >> ~/.bash_profile

      source ~/.bash_profile
      docker run hello-world
    "
  when: docker_availability.rc == 1

- name: Put GOOGLE_APPLICATION_CREDENTIALS to systemd unit
  become_user: trs-user
  copy:
    src: .config/systemd/user/docker.service
    dest: /home/trs-user/.config/systemd/user/
  notify: restart rootless docker

- name: Put GCP key file
  become_user: trs-user
  copy:
    src: trs-suzuran-dev-0eac1ce74875.json
    dest: /home/trs-user/
  notify: restart rootless docker

- name: Clone
  ansible.builtin.git:
    repo: https://github.com/keyasuda/trip-routing-system.git
    dest: /home/trs-user/app/trip_routing_system
    force: yes
  become_user: trs-user

- name: Put docker-conpose.yml
  become_user: trs-user
  template:
    src: docker-compose.yml
    dest: /home/trs-user/app/trip_routing_system/

- name: Put GSI tile config
  become_user: trs-user
  copy:
    src: production.local.yml
    dest: /home/trs-user/app/trip_routing_system/config/settings/

- name: Put prod-proxy config
  become_user: trs-user
  copy:
    src: nginx.conf
    dest: /home/trs-user/app/trip_routing_system/vendor/docker/prod-proxy/

- name: Docker pull
  become_user: trs-user
  shell: |
    /bin/bash -lc "
      cd /home/trs-user/app/trip_routing_system/
      docker compose pull
    "

- name: Restart app
  become_user: trs-user
  shell: |
    /bin/bash -lc "
      cd /home/trs-user/app/trip_routing_system/
      docker compose kill app && docker compose up app -d
    "
